export const ADD_INGREDENT = 'ADD_INGREDENT';
export const REMOVE_INGREDENT = 'REMOVE_INGREDENT';
export const RESET_INGREDENT = 'RESET_INGREDENT';
export const UPDATE_PURCHASABLE = 'UPDATE_PURCHASABLE';

export const LOAD_ORDER = 'LOAD_ORDER';
export const LOAD_ORDER_FAILED = 'LOAD_ORDER_FAILED';


export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';